import groups from "./AircraftGroups";

export type TransportCategory = "Bush / GA" | "Regional" | "Airliner" | "Cargo" | "VIP";
export type AircraftSilhouette = "airliner" | "regional" | "turboprop" | "ga" | "heavy" | "business";

export interface AircraftTransportPreset {
  id?: string;
  name: string;
  category: TransportCategory;
  silhouette: AircraftSilhouette;
  maxPassengers: number;
  maxCargoKg: number;
  cruiseSpeedKts: number;
  maxRangeNm: number;
  serviceCeilingFt: number;
  requiredRankTier?: number; // 0: Student, 1: Private Pilot, 2: Commercial, 3: Airline Captain
}

/**
 * Predefined Transport Specifications for GeoFS Aircraft
 */
export const AIRCRAFT_TRANSPORT_PRESETS: Record<string, AircraftTransportPreset> = {
  // General Aviation
  "1": {
    name: "Piper J-3 Cub",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 45,
    cruiseSpeedKts: 65,
    maxRangeNm: 190,
    serviceCeilingFt: 11500,
    requiredRankTier: 0,
  },
  "2": {
    name: "Cessna 172 Skyhawk",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 3,
    maxCargoKg: 120,
    cruiseSpeedKts: 122,
    maxRangeNm: 640,
    serviceCeilingFt: 14000,
    requiredRankTier: 0,
  },
  "3": {
    name: "Dassault Mirage 2000",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 100,
    cruiseSpeedKts: 550,
    maxRangeNm: 1800,
    serviceCeilingFt: 50000,
    requiredRankTier: 3,
  },
  "7": {
    name: "Supermarine Spitfire Mk IX",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 60,
    cruiseSpeedKts: 280,
    maxRangeNm: 650,
    serviceCeilingFt: 35000,
    requiredRankTier: 1,
  },
  "8": {
    name: "Alphajet",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 80,
    cruiseSpeedKts: 450,
    maxRangeNm: 1500,
    serviceCeilingFt: 48000,
    requiredRankTier: 1,
  },
  "9": {
    name: "Major Tom (Hot Air Balloon)",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 2,
    maxCargoKg: 60,
    cruiseSpeedKts: 20,
    maxRangeNm: 35,
    serviceCeilingFt: 10000,
    requiredRankTier: 0,
  },
  "11": {
    name: "SZD-48-3 Jantar (Glider)",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 20,
    cruiseSpeedKts: 70,
    maxRangeNm: 150,
    serviceCeilingFt: 15000,
    requiredRankTier: 0,
  },
  "15": {
    name: "North American P-51D Mustang",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 90,
    cruiseSpeedKts: 315,
    maxRangeNm: 1400,
    serviceCeilingFt: 41900,
    requiredRankTier: 1,
  },
  "18": {
    name: "General Dynamics F-16 Fighting Falcon",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 150,
    cruiseSpeedKts: 575,
    maxRangeNm: 2280,
    serviceCeilingFt: 50000,
    requiredRankTier: 3,
  },
  "20": {
    name: "Aérospatiale/BAC Concorde",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 100,
    maxCargoKg: 8500,
    cruiseSpeedKts: 1150,
    maxRangeNm: 3900,
    serviceCeilingFt: 60000,
    requiredRankTier: 3,
  },
  "27": {
    name: "Sukhoi Su-35 Flanker-E",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 180,
    cruiseSpeedKts: 600,
    maxRangeNm: 2500,
    serviceCeilingFt: 55000,
    requiredRankTier: 3,
  },
  "29": {
    name: "Boeing F/A-18F Super Hornet",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 150,
    cruiseSpeedKts: 560,
    maxRangeNm: 1800,
    serviceCeilingFt: 50000,
    requiredRankTier: 3,
  },
  "12": {
    name: "Pitts Special S-1",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 0,
    maxCargoKg: 30,
    cruiseSpeedKts: 150,
    maxRangeNm: 300,
    serviceCeilingFt: 15000,
    requiredRankTier: 0,
  },
  "13": {
    name: "Extra 300S",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 40,
    cruiseSpeedKts: 175,
    maxRangeNm: 420,
    serviceCeilingFt: 16000,
    requiredRankTier: 0,
  },
  "14": {
    name: "Douglas DC-3",
    category: "Regional",
    silhouette: "turboprop",
    maxPassengers: 28,
    maxCargoKg: 2700,
    cruiseSpeedKts: 180,
    maxRangeNm: 1300,
    serviceCeilingFt: 23200,
    requiredRankTier: 1,
  },
  "16": {
    name: "Beechcraft Baron 58",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 5,
    maxCargoKg: 450,
    cruiseSpeedKts: 202,
    maxRangeNm: 1050,
    serviceCeilingFt: 20688,
    requiredRankTier: 1,
  },
  "21": {
    name: "de Havilland Canada DHC-2 Beaver",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 6,
    maxCargoKg: 950,
    cruiseSpeedKts: 125,
    maxRangeNm: 455,
    serviceCeilingFt: 18000,
    requiredRankTier: 0,
  },
  "26": {
    name: "de Havilland Canada DHC-6 Twin Otter",
    category: "Regional",
    silhouette: "turboprop",
    maxPassengers: 19,
    maxCargoKg: 1850,
    cruiseSpeedKts: 160,
    maxRangeNm: 775,
    serviceCeilingFt: 25000,
    requiredRankTier: 1,
  },
  "28": {
    name: "Lockheed L-1049 Super Constellation",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 85,
    maxCargoKg: 6500,
    cruiseSpeedKts: 280,
    maxRangeNm: 2800,
    serviceCeilingFt: 24000,
    requiredRankTier: 2,
  },
  "40": {
    name: "Robin DR400",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 3,
    maxCargoKg: 110,
    cruiseSpeedKts: 135,
    maxRangeNm: 580,
    serviceCeilingFt: 14000,
    requiredRankTier: 0,
  },
  "51": {
    name: "Hughes 500D",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 4,
    maxCargoKg: 450,
    cruiseSpeedKts: 135,
    maxRangeNm: 335,
    serviceCeilingFt: 16000,
    requiredRankTier: 1,
  },
  "52": {
    name: "Bell 206 JetRanger",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 4,
    maxCargoKg: 500,
    cruiseSpeedKts: 115,
    maxRangeNm: 374,
    serviceCeilingFt: 13500,
    requiredRankTier: 1,
  },
  "102": {
    name: "Robinson R22",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 50,
    cruiseSpeedKts: 96,
    maxRangeNm: 200,
    serviceCeilingFt: 14000,
    requiredRankTier: 0,
  },

  // Regional Airliners & Turboprops
  "6": {
    name: "Embraer EMB 120 Brasilia",
    category: "Regional",
    silhouette: "turboprop",
    maxPassengers: 30,
    maxCargoKg: 3300,
    cruiseSpeedKts: 298,
    maxRangeNm: 945,
    serviceCeilingFt: 30000,
    requiredRankTier: 1,
  },
  "2003": {
    name: "Embraer E-Jet E190",
    category: "Regional",
    silhouette: "regional",
    maxPassengers: 106,
    maxCargoKg: 13000,
    cruiseSpeedKts: 440,
    maxRangeNm: 2400,
    serviceCeilingFt: 41000,
    requiredRankTier: 2,
  },
  "2769": {
    name: "Bombardier CRJ-700",
    category: "Regional",
    silhouette: "regional",
    maxPassengers: 70,
    maxCargoKg: 8500,
    cruiseSpeedKts: 445,
    maxRangeNm: 1500,
    serviceCeilingFt: 41000,
    requiredRankTier: 2,
  },
  "2864": {
    name: "Beechcraft Super King Air B200",
    category: "VIP",
    silhouette: "turboprop",
    maxPassengers: 9,
    maxCargoKg: 1100,
    cruiseSpeedKts: 280,
    maxRangeNm: 1580,
    serviceCeilingFt: 35000,
    requiredRankTier: 1,
  },
  "3054": {
    name: "Embraer Phenom 100",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 5,
    maxCargoKg: 600,
    cruiseSpeedKts: 390,
    maxRangeNm: 1178,
    serviceCeilingFt: 41000,
    requiredRankTier: 1,
  },
  "3140": {
    name: "Cessna Citation X",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 8,
    maxCargoKg: 850,
    cruiseSpeedKts: 525,
    maxRangeNm: 3460,
    serviceCeilingFt: 51000,
    requiredRankTier: 2,
  },
  "3460": {
    name: "ATR 72-600",
    category: "Regional",
    silhouette: "turboprop",
    maxPassengers: 72,
    maxCargoKg: 7500,
    cruiseSpeedKts: 275,
    maxRangeNm: 825,
    serviceCeilingFt: 25000,
    requiredRankTier: 1,
  },

  // Commercial Narrow-body & Wide-body Airliners
  "4": {
    name: "Boeing 737-800",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 189,
    maxCargoKg: 18200,
    cruiseSpeedKts: 450,
    maxRangeNm: 3115,
    serviceCeilingFt: 41000,
    requiredRankTier: 2,
  },
  "5": {
    name: "Boeing 777-300ER",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 396,
    maxCargoKg: 44000,
    cruiseSpeedKts: 490,
    maxRangeNm: 7370,
    serviceCeilingFt: 43100,
    requiredRankTier: 3,
  },
  "24": {
    name: "Airbus A380-800",
    category: "Airliner",
    silhouette: "heavy",
    maxPassengers: 555,
    maxCargoKg: 65000,
    cruiseSpeedKts: 490,
    maxRangeNm: 8000,
    serviceCeilingFt: 43000,
    requiredRankTier: 3,
  },
  "238": {
    name: "Airbus A320neo",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 180,
    maxCargoKg: 16600,
    cruiseSpeedKts: 450,
    maxRangeNm: 3500,
    serviceCeilingFt: 39800,
    requiredRankTier: 2,
  },
  "242": {
    name: "Boeing 787-9 Dreamliner",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 290,
    maxCargoKg: 35000,
    cruiseSpeedKts: 488,
    maxRangeNm: 7635,
    serviceCeilingFt: 43000,
    requiredRankTier: 3,
  },
  "1001": {
    name: "Boeing 777-200LR",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 317,
    maxCargoKg: 38000,
    cruiseSpeedKts: 490,
    maxRangeNm: 8555,
    serviceCeilingFt: 43100,
    requiredRankTier: 3,
  },
  "1003": {
    name: "Boeing 747-400",
    category: "Airliner",
    silhouette: "heavy",
    maxPassengers: 416,
    maxCargoKg: 58000,
    cruiseSpeedKts: 493,
    maxRangeNm: 7260,
    serviceCeilingFt: 45100,
    requiredRankTier: 3,
  },
  "1007": {
    name: "Antonov An-225 Mriya",
    category: "Cargo",
    silhouette: "heavy",
    maxPassengers: 0,
    maxCargoKg: 250000,
    cruiseSpeedKts: 430,
    maxRangeNm: 8300,
    serviceCeilingFt: 36000,
    requiredRankTier: 3,
  },
  "1025": {
    name: "Concorde",
    category: "VIP",
    silhouette: "airliner",
    maxPassengers: 100,
    maxCargoKg: 9500,
    cruiseSpeedKts: 1150,
    maxRangeNm: 3900,
    serviceCeilingFt: 60000,
    requiredRankTier: 3,
  },
  "2843": {
    name: "Airbus A350-900",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 325,
    maxCargoKg: 42000,
    cruiseSpeedKts: 488,
    maxRangeNm: 8100,
    serviceCeilingFt: 43100,
    requiredRankTier: 3,
  },
  "4140": {
    name: "Boeing 747-8F Freighter",
    category: "Cargo",
    silhouette: "heavy",
    maxPassengers: 0,
    maxCargoKg: 137700,
    cruiseSpeedKts: 490,
    maxRangeNm: 4390,
    serviceCeilingFt: 43000,
    requiredRankTier: 3,
  },
  "4949": {
    name: "Boeing C-17 Globemaster III",
    category: "Cargo",
    silhouette: "heavy",
    maxPassengers: 102,
    maxCargoKg: 77500,
    cruiseSpeedKts: 450,
    maxRangeNm: 2420,
    serviceCeilingFt: 45000,
    requiredRankTier: 3,
  },
  "1024": {
    name: "McDonnell Douglas F-15 Eagle",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 180,
    cruiseSpeedKts: 570,
    maxRangeNm: 2600,
    serviceCeilingFt: 60000,
    requiredRankTier: 3,
  },
  "2310": {
    name: "Grumman F-14 Tomcat",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 150,
    cruiseSpeedKts: 550,
    maxRangeNm: 1600,
    serviceCeilingFt: 50000,
    requiredRankTier: 3,
  },
  "2364": {
    name: "Eurofighter Typhoon",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 120,
    cruiseSpeedKts: 580,
    maxRangeNm: 2000,
    serviceCeilingFt: 55000,
    requiredRankTier: 3,
  },
  "2556": {
    name: "Fairchild Republic A-10 Thunderbolt II",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 200,
    cruiseSpeedKts: 300,
    maxRangeNm: 2200,
    serviceCeilingFt: 45000,
    requiredRankTier: 2,
  },
  "2581": {
    name: "Lockheed Martin F-22 Raptor",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 150,
    cruiseSpeedKts: 620,
    maxRangeNm: 1800,
    serviceCeilingFt: 65000,
    requiredRankTier: 3,
  },
  "2788": {
    name: "Antonov An-225 Mriya",
    category: "Cargo",
    silhouette: "heavy",
    maxPassengers: 0,
    maxCargoKg: 250000,
    cruiseSpeedKts: 430,
    maxRangeNm: 8300,
    serviceCeilingFt: 36000,
    requiredRankTier: 3,
  },
  "2808": {
    name: "Mitsubishi A6M Zero",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 50,
    cruiseSpeedKts: 200,
    maxRangeNm: 1600,
    serviceCeilingFt: 33000,
    requiredRankTier: 1,
  },
  "2857": {
    name: "Mikoyan MiG-29 Fulcrum",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 120,
    cruiseSpeedKts: 550,
    maxRangeNm: 1150,
    serviceCeilingFt: 55000,
    requiredRankTier: 3,
  },
  "2948": {
    name: "Lockheed Martin F-35 Lightning II",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 140,
    cruiseSpeedKts: 550,
    maxRangeNm: 1500,
    serviceCeilingFt: 50000,
    requiredRankTier: 3,
  },
  "2988": {
    name: "Sukhoi Su-27 Flanker",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 160,
    cruiseSpeedKts: 580,
    maxRangeNm: 2150,
    serviceCeilingFt: 62000,
    requiredRankTier: 3,
  },
  "3591": {
    name: "Lockheed SR-71 Blackbird",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 100,
    cruiseSpeedKts: 1800,
    maxRangeNm: 2900,
    serviceCeilingFt: 85000,
    requiredRankTier: 3,
  },
  "3617": {
    name: "Saab JAS 39 Gripen",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 120,
    cruiseSpeedKts: 560,
    maxRangeNm: 1700,
    serviceCeilingFt: 50000,
    requiredRankTier: 3,
  },
  "4251": {
    name: "Messerschmitt Bf 109",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 50,
    cruiseSpeedKts: 280,
    maxRangeNm: 450,
    serviceCeilingFt: 39000,
    requiredRankTier: 1,
  },
  "5229": {
    name: "McDonnell Douglas F-4 Phantom II",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 180,
    cruiseSpeedKts: 540,
    maxRangeNm: 1450,
    serviceCeilingFt: 60000,
    requiredRankTier: 3,
  },
  "5347": {
    name: "Northrop T-38 Talon",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 80,
    cruiseSpeedKts: 480,
    maxRangeNm: 950,
    serviceCeilingFt: 50000,
    requiredRankTier: 2,
  },
  "5405": {
    name: "Dassault Rafale",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 140,
    cruiseSpeedKts: 575,
    maxRangeNm: 2000,
    serviceCeilingFt: 52000,
    requiredRankTier: 3,
  },
  "5431": {
    name: "Sukhoi Su-57 Felon",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 160,
    cruiseSpeedKts: 600,
    maxRangeNm: 2100,
    serviceCeilingFt: 65000,
    requiredRankTier: 3,
  },
};

/**
 * Fallback preset categories based on aircraft group classifications
 */
export const CATEGORY_TRANSPORT_PRESETS: Record<string, AircraftTransportPreset> = {
  singleEngine: {
    name: "Single Engine Piston",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 3,
    maxCargoKg: 120,
    cruiseSpeedKts: 120,
    maxRangeNm: 600,
    serviceCeilingFt: 14000,
    requiredRankTier: 0,
  },
  twinPistonEngine: {
    name: "Twin Piston Aircraft",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 5,
    maxCargoKg: 450,
    cruiseSpeedKts: 190,
    maxRangeNm: 1000,
    serviceCeilingFt: 20000,
    requiredRankTier: 1,
  },
  twinTurboprop: {
    name: "Twin Turboprop Regional",
    category: "Regional",
    silhouette: "turboprop",
    maxPassengers: 19,
    maxCargoKg: 2000,
    cruiseSpeedKts: 260,
    maxRangeNm: 1200,
    serviceCeilingFt: 25000,
    requiredRankTier: 1,
  },
  twinjetNarrowBody: {
    name: "Narrow-body Jet Airliner",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 160,
    maxCargoKg: 16000,
    cruiseSpeedKts: 450,
    maxRangeNm: 3000,
    serviceCeilingFt: 39000,
    requiredRankTier: 2,
  },
  twinjetWideBody: {
    name: "Wide-body Jet Airliner",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 350,
    maxCargoKg: 40000,
    cruiseSpeedKts: 490,
    maxRangeNm: 7000,
    serviceCeilingFt: 43000,
    requiredRankTier: 3,
  },
  quadjet: {
    name: "Heavy Quadjet Airliner",
    category: "Airliner",
    silhouette: "heavy",
    maxPassengers: 450,
    maxCargoKg: 55000,
    cruiseSpeedKts: 490,
    maxRangeNm: 7500,
    serviceCeilingFt: 43000,
    requiredRankTier: 3,
  },
  privateJet: {
    name: "Business Jet",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 8,
    maxCargoKg: 800,
    cruiseSpeedKts: 440,
    maxRangeNm: 2200,
    serviceCeilingFt: 43000,
    requiredRankTier: 2,
  },
  fighterJet: {
    name: "Fighter Jet",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 1,
    maxCargoKg: 100,
    cruiseSpeedKts: 550,
    maxRangeNm: 1200,
    serviceCeilingFt: 50000,
    requiredRankTier: 2,
  },
  fighter: {
    name: "Historical Warbird",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 60,
    cruiseSpeedKts: 260,
    maxRangeNm: 650,
    serviceCeilingFt: 25000,
    requiredRankTier: 1,
  },
  glider: {
    name: "Glider / Sailplane",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 1,
    maxCargoKg: 20,
    cruiseSpeedKts: 65,
    maxRangeNm: 120,
    serviceCeilingFt: 15000,
    requiredRankTier: 0,
  },
  heavy: {
    name: "Heavy Transport / Cargo",
    category: "Cargo",
    silhouette: "heavy",
    maxPassengers: 0,
    maxCargoKg: 100000,
    cruiseSpeedKts: 450,
    maxRangeNm: 4500,
    serviceCeilingFt: 40000,
    requiredRankTier: 3,
  },
  heavyCargo: {
    name: "Heavy Cargo Transport",
    category: "Cargo",
    silhouette: "heavy",
    maxPassengers: 0,
    maxCargoKg: 120000,
    cruiseSpeedKts: 460,
    maxRangeNm: 5000,
    serviceCeilingFt: 43000,
    requiredRankTier: 3,
  },
  helicopter: {
    name: "Helicopter",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 4,
    maxCargoKg: 450,
    cruiseSpeedKts: 120,
    maxRangeNm: 350,
    serviceCeilingFt: 15000,
    requiredRankTier: 1,
  },
  turbopropCommuter: {
    name: "Turboprop Commuter",
    category: "Regional",
    silhouette: "turboprop",
    maxPassengers: 48,
    maxCargoKg: 4500,
    cruiseSpeedKts: 280,
    maxRangeNm: 1000,
    serviceCeilingFt: 25000,
    requiredRankTier: 1,
  },
  regionalJet: {
    name: "Regional Jet",
    category: "Regional",
    silhouette: "regional",
    maxPassengers: 85,
    maxCargoKg: 9500,
    cruiseSpeedKts: 440,
    maxRangeNm: 1800,
    serviceCeilingFt: 41000,
    requiredRankTier: 2,
  },
  businessJet: {
    name: "Business Jet",
    category: "VIP",
    silhouette: "business",
    maxPassengers: 8,
    maxCargoKg: 850,
    cruiseSpeedKts: 460,
    maxRangeNm: 2500,
    serviceCeilingFt: 45000,
    requiredRankTier: 2,
  },
  wideBody4Engine: {
    name: "Wide-body 4-Engine Heavy",
    category: "Airliner",
    silhouette: "heavy",
    maxPassengers: 450,
    maxCargoKg: 60000,
    cruiseSpeedKts: 490,
    maxRangeNm: 7500,
    serviceCeilingFt: 43000,
    requiredRankTier: 3,
  },
  narrowBody4Engine: {
    name: "Narrow-body 4-Engine",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 140,
    maxCargoKg: 14000,
    cruiseSpeedKts: 420,
    maxRangeNm: 3500,
    serviceCeilingFt: 38000,
    requiredRankTier: 2,
  },
  trijet: {
    name: "Trijet Airliner",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 280,
    maxCargoKg: 35000,
    cruiseSpeedKts: 480,
    maxRangeNm: 5500,
    serviceCeilingFt: 42000,
    requiredRankTier: 3,
  },
  twinjetNarrowBody2: {
    name: "Narrow-body Jet Airliner",
    category: "Airliner",
    silhouette: "airliner",
    maxPassengers: 160,
    maxCargoKg: 16000,
    cruiseSpeedKts: 450,
    maxRangeNm: 3000,
    serviceCeilingFt: 39000,
    requiredRankTier: 2,
  },
  rearMountedTwinJet: {
    name: "Rear-mounted Twinjet",
    category: "Regional",
    silhouette: "regional",
    maxPassengers: 100,
    maxCargoKg: 11000,
    cruiseSpeedKts: 440,
    maxRangeNm: 2200,
    serviceCeilingFt: 41000,
    requiredRankTier: 2,
  },
  default: {
    name: "Standard Aircraft",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 3,
    maxCargoKg: 150,
    cruiseSpeedKts: 130,
    maxRangeNm: 600,
    serviceCeilingFt: 14000,
    requiredRankTier: 0,
  },
};

/**
 * Helper to find aircraft category group from AircraftGroups.ts
 */
export function findAircraftGroup(aircraftId: string | number): string | null {
  const idStr = String(aircraftId);
  for (const [groupName, ids] of Object.entries(groups)) {
    if (Array.isArray(ids) && ids.includes(idStr)) {
      return groupName;
    }
  }
  return null;
}

/**
 * Resolves transport preset for any aircraft ID, group, or live GeoFS physics
 */
export function getAircraftTransportPreset(
  aircraftId?: string | number,
  fallbackCategory?: string,
  massKg: number = 2000
): AircraftTransportPreset {
  const geofs = (unsafeWindow as any).geofs;
  const curDef = geofs?.aircraft?.instance?.definition;
  const curId = geofs?.aircraft?.instance?.id;

  if (aircraftId !== undefined && aircraftId !== null) {
    const idStr = String(aircraftId);
    if (AIRCRAFT_TRANSPORT_PRESETS[idStr]) {
      return { ...AIRCRAFT_TRANSPORT_PRESETS[idStr], id: idStr };
    }

    const groupName = findAircraftGroup(idStr);
    if (groupName && CATEGORY_TRANSPORT_PRESETS[groupName]) {
      return { ...CATEGORY_TRANSPORT_PRESETS[groupName], id: idStr };
    }
  }

  // Dynamic physics inspection from active GeoFS Beta v4 aircraft definition
  if (curDef && (aircraftId === undefined || String(aircraftId) === String(curId))) {
    const liveMass = Number(curDef.mass) || massKg;
    const vno = Number(curDef.Vspeeds?.VNO) || Math.round(Number(curDef.Vspeeds?.VNE || 0) * 0.8) || 0;
    const hasJet = Array.isArray(curDef.engines) && curDef.engines.some((e: any) => e.afterBurnerThrust || (e.thrust && e.thrust > 25000));
    const nameLower = String(curDef.name || "").toLowerCase();
    const isFighter = nameLower.includes("fighter") || nameLower.includes("f-") || nameLower.includes("su-") || nameLower.includes("mig-") || (hasJet && liveMass < 35000 && vno > 350);

    if (isFighter) {
      const speed = Math.max(480, Math.round(vno || 560));
      return {
        id: String(curId || "custom"),
        name: curDef.name || "Fighter Jet",
        category: "VIP",
        silhouette: "business",
        maxPassengers: 1,
        maxCargoKg: 150,
        cruiseSpeedKts: speed,
        maxRangeNm: 2200,
        serviceCeilingFt: 50000,
        requiredRankTier: 3,
      };
    }

    if (liveMass > 150000) {
      return {
        id: String(curId || "custom"),
        name: curDef.name || "Heavy Transport",
        category: "Cargo",
        silhouette: "heavy",
        maxPassengers: 0,
        maxCargoKg: Math.round(liveMass * 0.45),
        cruiseSpeedKts: Math.max(420, vno || 480),
        maxRangeNm: 6500,
        serviceCeilingFt: 43000,
        requiredRankTier: 3,
      };
    } else if (liveMass > 60000) {
      return {
        id: String(curId || "custom"),
        name: curDef.name || "Wide-body Airliner",
        category: "Airliner",
        silhouette: "airliner",
        maxPassengers: Math.min(450, Math.round(liveMass / 250)),
        maxCargoKg: Math.round(liveMass * 0.25),
        cruiseSpeedKts: Math.max(430, vno || 470),
        maxRangeNm: 5500,
        serviceCeilingFt: 41000,
        requiredRankTier: 2,
      };
    } else if (liveMass > 20000) {
      return {
        id: String(curId || "custom"),
        name: curDef.name || "Narrow-body Airliner",
        category: "Airliner",
        silhouette: "airliner",
        maxPassengers: Math.min(189, Math.round(liveMass / 220)),
        maxCargoKg: Math.round(liveMass * 0.2),
        cruiseSpeedKts: Math.max(400, vno || 440),
        maxRangeNm: 3200,
        serviceCeilingFt: 39000,
        requiredRankTier: 2,
      };
    } else if (liveMass > 5000) {
      return {
        id: String(curId || "custom"),
        name: curDef.name || "Regional Aircraft",
        category: "Regional",
        silhouette: "regional",
        maxPassengers: Math.min(70, Math.round(liveMass / 200)),
        maxCargoKg: Math.round(liveMass * 0.18),
        cruiseSpeedKts: Math.max(250, vno || 320),
        maxRangeNm: 1600,
        serviceCeilingFt: 32000,
        requiredRankTier: 1,
      };
    } else {
      return {
        id: String(curId || "custom"),
        name: curDef.name || "General Aviation",
        category: "Bush / GA",
        silhouette: "ga",
        maxPassengers: Math.max(1, Math.min(5, Math.round(liveMass / 400))),
        maxCargoKg: Math.round(liveMass * 0.12),
        cruiseSpeedKts: Math.max(90, vno || 125),
        maxRangeNm: 650,
        serviceCeilingFt: 15000,
        requiredRankTier: 0,
      };
    }
  }

  if (fallbackCategory && CATEGORY_TRANSPORT_PRESETS[fallbackCategory]) {
    return { ...CATEGORY_TRANSPORT_PRESETS[fallbackCategory] };
  }

  // Mass-based estimation fallback
  if (massKg > 150000) {
    return {
      name: "Super Heavy Transport",
      category: "Cargo",
      silhouette: "heavy",
      maxPassengers: 0,
      maxCargoKg: Math.round(massKg * 0.45),
      cruiseSpeedKts: 480,
      maxRangeNm: 6500,
      serviceCeilingFt: 41000,
      requiredRankTier: 3,
    };
  } else if (massKg > 60000) {
    return {
      name: "Wide-body Transport",
      category: "Airliner",
      silhouette: "airliner",
      maxPassengers: Math.min(450, Math.round(massKg / 250)),
      maxCargoKg: Math.round(massKg * 0.25),
      cruiseSpeedKts: 470,
      maxRangeNm: 5500,
      serviceCeilingFt: 41000,
      requiredRankTier: 2,
    };
  } else if (massKg > 20000) {
    return {
      name: "Narrow-body Transport",
      category: "Airliner",
      silhouette: "airliner",
      maxPassengers: Math.min(189, Math.round(massKg / 220)),
      maxCargoKg: Math.round(massKg * 0.2),
      cruiseSpeedKts: 440,
      maxRangeNm: 3000,
      serviceCeilingFt: 39000,
      requiredRankTier: 2,
    };
  } else if (massKg > 5000) {
    return {
      name: "Regional Transport",
      category: "Regional",
      silhouette: "regional",
      maxPassengers: Math.min(50, Math.round(massKg / 200)),
      maxCargoKg: Math.round(massKg * 0.18),
      cruiseSpeedKts: 320,
      maxRangeNm: 1500,
      serviceCeilingFt: 30000,
      requiredRankTier: 1,
    };
  }

  return {
    name: "General Aviation Transport",
    category: "Bush / GA",
    silhouette: "ga",
    maxPassengers: 3,
    maxCargoKg: 120,
    cruiseSpeedKts: 120,
    maxRangeNm: 600,
    serviceCeilingFt: 14000,
    requiredRankTier: 0,
  };
}
